#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import platform
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


def _git(cmd: list[str], cwd: Path) -> str | None:
    try:
        out = subprocess.check_output(cmd, cwd=str(cwd), stderr=subprocess.DEVNULL)
        return out.decode().strip()
    except Exception:
        return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-id", required=True)
    args = ap.parse_args()

    repo = Path(__file__).resolve().parents[1]
    reports_dir = repo / "reports" / args.run_id
    reports_dir.mkdir(parents=True, exist_ok=True)

    meta = {
        "run_id": args.run_id,
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "cwd": str(repo),
        "user": os.getenv("USER") or os.getenv("USERNAME") or "unknown",
        "host": platform.node(),
        "platform": platform.platform(),
        "python": sys.version.split()[0],
        "git_commit": _git(["git", "rev-parse", "HEAD"], repo),
        "git_branch": _git(["git", "branch", "--show-current"], repo),
        "note": "generated by tools/evidence.py",
    }

    (reports_dir / "meta.json").write_text(json.dumps(meta, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    summary = reports_dir / "summary.md"
    if not summary.exists():
        summary.write_text(
            f"# Summary\n\nRUN_ID: `{args.run_id}`\n\n"
            "## What changed\n- \n\n"
            "## Commands / Outputs\n- \n\n"
            "## Notes\n- \n",
            encoding="utf-8",
        )

    decision = reports_dir / "decision.md"
    if not decision.exists():
        decision.write_text(
            f"# Decision\n\nRUN_ID: `{args.run_id}`\n\n"
            "## Why\n- \n\n"
            "## Options considered\n- \n\n"
            "## Risks / Rollback\n- \n",
            encoding="utf-8",
        )

    print(f"OK: wrote {reports_dir/'meta.json'}")
    print(f"OK: ensured {summary}")
    print(f"OK: ensured {decision}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
